# Generated by Django 3.1.12 on 2025-03-15 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(default=main.models.CustomUser.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('voltaje', models.IntegerField(default=120)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_fabricacion', models.DateField(auto_now_add=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceConsumption',
            fields=[
                ('id', models.CharField(default=main.models.CustomUser.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('potencia', models.FloatField(default=0)),
                ('corriente', models.FloatField(default=0)),
                ('voltaje', models.FloatField(default=0)),
                ('consumo', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'device_consumption',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.CharField(default=main.models.CustomUser.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('fecha_adquisicion', models.DateTimeField(auto_now_add=True)),
                ('nombre_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('apagado_periodico', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.CharField(default=main.models.UserSession.generate_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='user_sessio_user_id_bb1b83_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='user_sessio_session_cc84b9_idx'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='dispositivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='main.device'),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceconsumption',
            name='user_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='main.userdevice'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('usuario', 'dispositivo')},
        ),
    ]
