# Generated by Django 3.1.12 on 2025-03-15 15:15

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250315_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceConsumption',
            fields=[
                ('id', models.CharField(default=main.models.ApplianceConsumption.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('potencia', models.FloatField(default=0)),
                ('corriente', models.FloatField(default=0)),
                ('voltaje', models.FloatField(default=0)),
                ('consumo', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'appliance_consumption',
            },
        ),
        migrations.CreateModel(
            name='ConnectedAppliance',
            fields=[
                ('id', models.CharField(default=main.models.ConnectedAppliance.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('voltaje', models.IntegerField(default=120)),
                ('fecha_conexion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('apagado_periodico', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'connected_appliances',
            },
        ),
        migrations.RemoveField(
            model_name='deviceconsumption',
            name='user_device',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_sessio_user_id_bb1b83_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_sessio_session_cc84b9_idx',
        ),
        migrations.RemoveField(
            model_name='device',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='device',
            name='voltaje',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.CharField(default=main.models.Device.generate_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='id',
            field=models.CharField(default=main.models.UserDevice.generate_id, editable=False, max_length=24, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='DeviceConsumption',
        ),
        migrations.AddField(
            model_name='connectedappliance',
            name='user_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrodomesticos', to='main.userdevice'),
        ),
        migrations.AddField(
            model_name='applianceconsumption',
            name='appliance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='main.connectedappliance'),
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='apagado_periodico',
        ),
    ]
