# Generated by Django 3.1.12 on 2025-03-17 21:25

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20250315_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdevice',
            name='dispositivo',
        ),
        migrations.RemoveField(
            model_name='userdevice',
            name='usuario',
        ),
        migrations.AddField(
            model_name='applianceconsumption',
            name='frecuencia',
            field=models.FloatField(default=60.0),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='dispositivo_id',
            field=models.CharField(default='temporary', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='usuario_id',
            field=models.CharField(default='temporary', max_length=24),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ApplianceAlert',
            fields=[
                ('id', models.CharField(default=main.models.ApplianceAlert.generate_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('atendida', models.BooleanField(default=False)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='main.connectedappliance')),
            ],
            options={
                'db_table': 'appliance_alerts',
            },
        ),
    ]
